

/* Create Tables */

CREATE TABLE ACCOUNTS
(
	ACCOUNT_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'アカウントID',
	USER_ID BIGINT NOT NULL COMMENT 'ユーザーID',
	ACCOUNT_NAME VARCHAR(20) NOT NULL COMMENT 'アカウント名',
	AVATAR VARCHAR(255) COMMENT 'アバター',
	ACCOUNT_STATUS CHAR(3) NOT NULL COMMENT 'アカウントステータス',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	VERSION_NO INT NOT NULL COMMENT 'バージョンナンバー',
	PRIMARY KEY (ACCOUNT_ID)
) COMMENT = 'アカウント';


CREATE TABLE ACCOUNT_FOLLOWINGS
(
	FOLLOWER_ID BIGINT NOT NULL COMMENT 'フォロワーID',
	FOLLOWEE_ID BIGINT NOT NULL COMMENT 'フォロイーID',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードの登録日時',
	CONSTRAINT UQ_FOLLOWER_ID_AND_FOLLOWEE_ID UNIQUE (FOLLOWER_ID, FOLLOWEE_ID)
) COMMENT = 'アカウントフォローイング';


CREATE TABLE TWEETS
(
	TWEET_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ツイートID',
	ACCOUNT_ID BIGINT NOT NULL COMMENT 'アカウントID',
	TWEET_TEXT VARCHAR(140) NOT NULL COMMENT 'ツイートテキスト',
	TWEET_STATUS CHAR(3) NOT NULL COMMENT 'ツイートステータス : ENA or DIS',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時 : レコードの登録日時',
	PRIMARY KEY (TWEET_ID)
) COMMENT = 'ツイート';


CREATE TABLE USERS
(
	USER_ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
	PASSWORD CHAR(60) NOT NULL COMMENT 'パスワード',
	EMAIL VARCHAR(150) NOT NULL UNIQUE COMMENT 'メールアドレス',
	USER_STATUS CHAR(3) NOT NULL COMMENT 'ユーザーステータス',
	REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
	UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
	VERSION_NO INT NOT NULL COMMENT 'バージョンナンバー',
	PRIMARY KEY (USER_ID)
) COMMENT = 'ユーザー';



/* Create Indexes */

CREATE UNIQUE INDEX IX_ACCOUNTS_ACCOUNT_ID USING BTREE ON ACCOUNTS (ACCOUNT_ID ASC);
CREATE INDEX IX_ACCOUNTS_USER_ID USING BTREE ON ACCOUNTS (USER_ID ASC);
CREATE INDEX IX_ACCOUNTS_ACCOUNT_NAME USING BTREE ON ACCOUNTS (ACCOUNT_NAME ASC);
CREATE INDEX IX_ACCOUNT_FOLLOWINGS_FOLLOWER_ID USING BTREE ON ACCOUNT_FOLLOWINGS (FOLLOWER_ID ASC);
CREATE INDEX IX_ACCOUNT_FOLLOWINGS_FOLLOWEE_ID USING BTREE ON ACCOUNT_FOLLOWINGS (FOLLOWEE_ID ASC);
CREATE INDEX IX_TWEETS_TWEET_ID USING BTREE ON TWEETS (TWEET_ID ASC);
CREATE INDEX IX_TWEETS_ACCOUNT_ID USING BTREE ON TWEETS (ACCOUNT_ID ASC);
CREATE INDEX IX_USERS_USER_ID USING BTREE ON USERS (USER_ID ASC);



/* Create Foreign Keys */

ALTER TABLE ACCOUNT_FOLLOWINGS
	ADD CONSTRAINT FK_ACCOUNT_FOLLOWINGS_ACCOUNTS_FOLLOWER_ID FOREIGN KEY (FOLLOWER_ID)
	REFERENCES ACCOUNTS (ACCOUNT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ACCOUNT_FOLLOWINGS
	ADD CONSTRAINT FK_ACCOUNT_FOLLOWINGS_ACCOUNTS_FOLLOWEE_ID FOREIGN KEY (FOLLOWEE_ID)
	REFERENCES ACCOUNTS (ACCOUNT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TWEETS
	ADD CONSTRAINT FK_TWEETS_ACCOUNTS FOREIGN KEY (ACCOUNT_ID)
	REFERENCES ACCOUNTS (ACCOUNT_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ACCOUNTS
	ADD CONSTRAINT FK_ACCOUNTS_USERS FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



